# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    rate_limiter:
        contact_form:
            policy: fixed_window
            limit: 5
            interval: '15 minutes'
        guestbook_form:
            policy: fixed_window
            limit: 3
            interval: '30 minutes'
        membership_application:
            policy: fixed_window
            limit: 3
            interval: '1 hour'
        event_help_form:
            policy: fixed_window
            limit: 5
            interval: '1 hour'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        rate_limiter:
            contact_form:
                policy: no_limit
            guestbook_form:
                policy: no_limit
            membership_application:
                policy: no_limit
            event_help_form:
                policy: no_limit

when@dev:
    framework:
        rate_limiter:
            membership_application:
                policy: no_limit
            event_help_form:
                policy: no_limit
