security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ROLE_MANAGE
            - ROLE_SYSTEM_MANAGE
        ROLE_MODULE_PAGES_PUBLISHER: ROLE_MODULE_PAGES_EDITOR
        ROLE_MODULE_PAGES_MODERATOR: ROLE_MODULE_PAGES_EDITOR
        ROLE_MODULE_PAGES_EDITOR: ROLE_MODULE_PAGES_VIEWER
        ROLE_MODULE_ACTIVITIES_EDITOR: ROLE_MODULE_ACTIVITIES_VIEWER
        ROLE_MODULE_GUESTBOOK_EDITOR: ROLE_MODULE_GUESTBOOK_VIEWER
        ROLE_MODULE_CONTACT_REQUESTS_EDITOR: ROLE_MODULE_CONTACT_REQUESTS_VIEWER
        ROLE_MODULE_EVENT_HELPERS_EDITOR: ROLE_MODULE_EVENT_HELPERS_VIEWER
        ROLE_MODULE_MEMBERSHIP_APPLICATIONS_EDITOR: ROLE_MODULE_MEMBERSHIP_APPLICATIONS_VIEWER
        ROLE_MODULE_USER_MANAGEMENT_EDITOR: ROLE_MODULE_USER_MANAGEMENT_VIEWER

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        cms_users:
            id: App\UI\IdentityAccess\Security\AuthenticatedUserProvider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            stateless: true
            provider: cms_users
            access_token:
                token_handler: App\UI\IdentityAccess\Security\AccessTokenHandler
                token_extractors:
                    - App\UI\IdentityAccess\Security\CookieAccessTokenExtractor

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/api/admin, roles: ROLE_CMS }
        - { path: ^/admin, roles: PUBLIC_ACCESS }
